# Generated by Django 4.2.4 on 2023-08-24 07:28

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('초중고', models.CharField(choices=[('초등학교', '초등학교'), ('중학교', '중학교'), ('고등학교', '고등학교'), ('일반', '일반')], max_length=4)),
                ('학년', models.CharField(choices=[('1학년', '1'), ('2학년', '2'), ('3학년', '3'), ('4학년', '4'), ('5학년', '5'), ('6학년', '6'), ('일반', '0')], max_length=3)),
                ('직업', models.CharField(choices=[('선생님', '선생님'), ('학생', '학생'), ('학부모님', '학부모님')], default='학생', max_length=4)),
                ('본인핸드폰번호', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
                ('부모님핸드폰번호', models.CharField(blank=True, max_length=16, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{8,15}$')])),
            ],
        ),
    ]
